### ISSUE TITLE
Create other issues

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/SINAPSE#2]
Alex,

This SINAPSE repository is meant to document all the work that you have done for the lab.  If you create scripts, or materials that I need to see, please make a directory here and place that content in those directories.

-- Please make a set of issues of tasks that you completed, and tasks that you need to work on.

Hans

**Comment by abpwrs** [comment]
@hjmjohnson Do you want to use the Github Projects tab in this repository to track issue status? or just use issues?

**Comment by hjmjohnson** [comment]
@abpwrs Just issues for now.  I'm using zenhub instead of projects.
