### ISSUE TITLE
node project structure

### ISSUE THREAD

**Issue by abpwrs** [BRAINSia/SINAPSE#8]
@chasejohnson3 I noticed that your Identify Putamen project has a node_modules directory in it. Was this purposeful?       
Generally, you'll want to add that folder to your `.gitignore` and instead have project dependencies tracked using `package.json` and `package-lock.json` files. You can make these files using npm. [helpful blog post](https://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/)

**Comment by chasejohnson3** [comment]
I have removed the node_modules directory and added a package.json file.
