### ISSUE TITLE
exporting conda envs

### ISSUE THREAD

**Issue by abpwrs** [BRAINSia/SINAPSE#9]
The current [environment.yml](https://github.com/BRAINSia/SINAPSE/commit/fb56d8a03daf931dea72960c0a4717ae4bc0da61) file in 20190313_EyeDistance contains a help message. You will want it to look like [this](https://github.com/BRAINSia/SINAPSE/blob/master/20190308_ImageAugScript2D/environment.yml). These [docs](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment) on conda env management may be helpful.

**Comment by chasejohnson3** [comment]
I have created a new version of the environment.yml file.  I see some odd lines reading "!!python/unicode".  @abpwrs could you take a look to see if it looks like a working environment file?

**Comment by chasejohnson3** [comment]
Created a working environment.yml file
